# Generated by Django 3.0 on 2019-12-24 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('Title', models.CharField(max_length=255)),
                ('Credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('administrator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorID', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('timeStamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personID', models.IntegerField()),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('hireDate', models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 24, 11, 51, 31, 78795))),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentID', models.IntegerField()),
                ('grade', models.CharField(max_length=255)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Person')),
            ],
        ),
        migrations.CreateModel(
            name='OnsiteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('days', models.IntegerField()),
                ('time', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Person')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='departmentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Department'),
        ),
    ]
